version: '3'

services:
  # Servicio de PHP
  app:
    build:
      args:
        user: gaming_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gaming-hardware-app
    container_name: gaming-hardware-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - gaming-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: gaming-hardware-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - gaming-network

  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: gaming-hardware-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - gaming-network

networks:
  gaming-network:
    driver: bridge