services:
  - type: web
    name: gaming-hardware-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    port: 80
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: "base64:l5EjHex47Xjj9ohXABWYogneBviDG2v+arwfai7JEeQ="
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync